# Generated by Django 4.1.1 on 2022-09-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeriadoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Feriado')),
                ('dia', models.IntegerField(verbose_name='Data')),
                ('mes', models.IntegerField(verbose_name='Mês')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
            ],
        ),
    ]
